import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";

const font = Mulish({
  subsets: ["latin", "cyrillic"],
});

export const metadata: Metadata = {
  title: "Втк",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-[#dae2ed]`}>{children}</body>
    </html>
  );
}
