import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";

const font = Mulish();

export const metadata: Metadata = {
  title: "Втк",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${font.className} bg-[#dae2ed]`}>
        {children}
        <Toaster />
      </body>
    </html>
  );
}
