import { Header } from "@/src/widgets/Header";
import { Sidebar } from "@/src/widgets/Sidebar/Sidebar";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Панель администратора",
  description: "Generated by create next app",
};

export default function TeacherLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex m-5 gap-5 container mx-auto">
      <Sidebar />
      <div className="w-full gap-5 flex flex-col">
        <Header />
        <div className="grid grid-flow-col gap-5">{children}</div>
      </div>
    </div>
  );
}
